"""
    Falta terminar
"""

productions = {
    1: ["begin", "VARIABLES", "ESTATUTOS", "end"],
    2: ["{", "DECLARACION", "}", "VARIABLES"],
    3: ["ε"], 4: ["LISTA", ":", "TIPO", ";", "DECLARACION"],
    5: ["ε"], 6: ["integer"], 7: ["real"], 8: ["string"], 9: ["bolean"],
    10: ["list"], 11: ["identificador", "EXTRA", "LISTAPRIMA"],
    12: [",", "LISTA"], 13: ["ε"], 14: ["=", "NUMERO_LISTA_NUMEROS"],
    15: ["NUMEROS"], 16: ["LISTA_NUMEROS"], 17: ["ε"],
    18: ["[", "NUMEROS", "]"], 19: ["numero", "LISTANUMERO"],
    20: [",", "NUMEROS"], 21: ["ε"], 22: ["ESTATUTO", ".", "ESTATUTOS"],
    23: ["ε"], 24: ["if", "CONDICION", "{", "ESTATUTOS", "}", "ELSE"],
    25: ["else", "{", "ESTATUTOS", "}"],
    26: ["for", "(", "identificador", "=", "ESTATUTO1"],
    27: ["LISTAVALORES", ")", "{", "ESTATUTOS", "}"],
    28: ["EXPRESION", ";", "identificador", "OPERADOR", "EXPRESION", ";", "INCREDECRE", ")", "{", "ESTATUTOS", "}"],
    29: ["LISTAORANGO", "{", "ESTATUTOS", "}"], 30: ["identificador", "SIGNO"],
    31: ["[", "IDENTIFICADOROVALOR", ":", "IDENTIFICADOROVALOR", "]"],
    32: ["identificador"], 33: ["[", "LISTA_VALORES", "]"],
    34: ["IDENTIFICADOROVALOR", "LISTAVALORESPRIMA"], 35: ["identificador"],
    36: ["numero"], 37: [",", "LISTA_VALORES"], 38: ["ε"],
    39: ["while", "CONDICION", "{", "ESTATUTOS", "}"],
    40: ["do", "identificador", "consecutive", "LISTAORANGO", "{", "ESTATUTOS", "}"],
    41: ["repeat", "{", "ESTATUTOS", "}", "CONDICION"],
    42: ["cases", "identificador", "{", "LISTACASES", "}"],
    43: ["print", "(", "IDENTIFICADOROVALOR", ")"], 44: ["read", "(", "identificador", ")"],
    45: ["break"], 46: ["ASIGNACION"], 47: ["=", "EXPRESION"],
    48: ["++"], 49: ["--"],
    50: ["case", "numero", "{", "ESTATUTOS", "}", "LISTACASES"],
    51: ["ε"], 52: ["(", "EXPRESION", "OPERADOR", "EXPRESION", ")"],
    53: ["~!", "(", "EXPRESION", "OPERADOR", "EXPRESION", ")"],
    54: ["IDENTIFICADOROVALOR", "in", "[", "IDENTIFICADOROVALOR", ":", "IDENTIFICADOROVALOR", "]"],
    55: ["="], 56: [">"], 57: ["<"], 58: [">="], 59: ["<="], 60: ["||"], 61: ["&&"],
    62: ["TERMINO", "EXPPRIMA"], 63: ["+", "TERMINO", "EXPPRIMA"],
    64: ["-", "TERMINO", "EXPPRIMA"], 65: ["ε"],
    66: ["FACTOR", "TERMPRIMO"], 67: ["*", "FACTOR", "TERMPRIMO"],
    68: ["/", "FACTOR", "TERMPRIMO"], 69: ["ε"],
    70: ["(", "EXPRESION", ")"], 71: ["identificador"],
    72: ["numero"]
}

# Diccionario de simbolos NO TERMINALES para acceder a la columna de la tabla sintactica
NT = {
    "P": 0,
    "VARIABLES": 1,
    "DECLARACION": 2,
    "TIPO": 3,
    "LISTA": 4,
    "LISTAPRIMA": 5,
    "EXTRA": 6,
    "NUMERO_LISTA_NUMEROS": 7,
    "LISTA_NUMEROS": 8,
    "NUMEROS": 9,
    "LISTANUMERO": 10,
    "ESTATUTOS": 11,
    "ESTATUTO": 12,
    "ELSE": 13,
    "ESTATUTO1": 14,
    "ESTATUTO2": 15,
    "INCREDECRE": 16,
    "LISTAORANGO": 17,
    "LISTAVALORES": 18,
    "LISTA_VALORES": 19,
    "IDENTIFICADOROVALOR": 20,
    "LISTAVALORESPRIMA": 21,
    "SIGNO": 22,
    "LISTACASES": 23,
    "CONDICION": 24,
    "OPERADOR": 25,
    "EXPRESION": 26,
    "EXPPRIMA": 27,
    "TERMINO": 28,
    "TERMPRIMO": 29,
    "FACTOR": 30,
    "ASIGNACION": 31
}

stack = ["$", "P"]
